######################## default configuration ####################
baseURL = "https://fuzztechnology.com"
title = "Fuzz Technology"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
#disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "G-DHZ70CGPQQ" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Information Security Program Development"
URL = "infosecprog"
weight = 3

[[menu.main]]
name = "Incident Response Program Development"
URL = "infosecprog"
weight = 4

[[menu.main]]
name = "Information Security Assessments"
URL = "assessments"
weight = 5

[[menu.main]]
name = "Physical Security Assessments"
URL = "psec"
weight = 6

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 7


[[menu.main]]
name = "Contact"
URL = "contact"
weight = 8

#[[menu.main]]
#name = "Sample Page"
#URL = "infosec"
#weight = 9

# only desktop menu
[[menu.desktop]]
name = "Contact"
URL = "contact"
weight = 1

# only desktop menu
[[menu.desktop]]
name = "Privacy"
URL = "privacy"
weight = 1

#################### default parameters ################################
[params]
# Meta data
description = "Fuzz Technology L.L.C. website"
author = "Nick Selby"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "Information and Physical Security Advisory Services"
image = "images/grassau.png"

# blog
[params.blog]
heading = "Our team executes quickly on organizational and protective strategies, then helps you replace us with qualified, empowered executives and managers to carry the program forward."

# call to action
[params.call_to_action]
enable = true
title = "Contact us for more information."
content = "You can send us an email or [book a convenient time](https://calendly.com/fuzztechnology) to discuss your challenges"
button_label = "Contact Us"
button_url = "contact"

# gallery
[params.gallery]
enable = false

[[params.gallery.gallery_item ]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item ]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "About Fuzz Technology, L.L.C."
content = "Fuzz Technology helps organizations understand and improve their security information and physical security posture and programs."
address = "PO Box 18 <br> Ghent, NY 12075"
hours = "Monday through Friday: 1000 – 1700 ET"
copyright = "Copyright &copy; 2021 Fuzz Technology, L.L.C."

############################# social site ########################
[params.social]
#yelp = "#"
#facebook = "#"
#twitter = "https://twitter.com/fuzztech"
#instagram = "#"
#email = "nselby [at] fuzztechnology [dot] com"
linkedin = "https://www.linkedin.com/company/76477399"
